### ISSUE TITLE
contract Whitelist deregister an address

### ISSUE THREAD

**Issue by akash2504** [ethfinex/nectar#1]
/// @dev deregister
  /// @param bannedUsers - Array of users to remove from the whitelist
  function deregister(address[] bannedUsers) onlyOwner {
    for (uint i = 0; i < bannedUsers.length; i++) {
      isOnList[bannedUsers[i]] = false;
    }
  }

The above derigester function only marks the mapping as false. I think you should delete the mapping to free your mappings. Otherwise the list will become huge

delete(isOnList[bannedUsers[i]]);

**Comment by plutoegg** [comment]
@akash2504 As it is a mapping and not an array setting it to false is fine.
